/* =====================================================================
   Seed data + i18n for بلدية النخيل / Al-Nakheel Municipality
   All data is bilingual. SITE.ar = Arabic, SITE.en = English.
   I18N holds translations for static UI strings.
   ===================================================================== */

window.I18N = {
  ar: {
    // Brand
    brandName: 'بلدية تفوح',
    brandSub:  'تابعة لوزارة الحكم المحلي ',
    // Topbar
    topAbout: 'عن البلدية', topNews: 'الأخبار', topContact: 'اتصل بنا', topA11y: 'الوصولية',
    userPortal: 'بوابة المستخدم', adminPortal: 'بوابة الإدارة',
    // Navbar
    navHome: 'الرئيسية', navAbout: 'عن البلدية', navServices: 'الخدمات',
    navNews: 'المركز الإعلامي', navContact: 'اتصل بنا',
    navCta: 'الخدمات الإلكترونية', backToSite: '← العودة للموقع',
    // Hero
    heroBadge: 'منصة الخدمات البلدية',
    heroTitle: 'نخدمكم على مدار الساعة،<br/>بأبسط الخطوات',
    heroLede: 'منصة موحّدة لجميع خدمات بلدية النخيل. أنجز معاملاتك، تتبّع طلباتك، وادفع رسومك إلكترونيًا بكل سهولة وأمان، من أي مكان وفي أي وقت.',
    heroCta1: 'ابدأ الخدمة', heroCta2: 'استكشف الخدمات',
    stat1v: '٤٢', stat1l: 'خدمة إلكترونية',
    stat2v: '٩٨٪', stat2l: 'نسبة الإنجاز',
    stat3v: '٢٤/٧', stat3l: 'متاح دائمًا',
    // Hero cards
    cardBuildTitle: 'طلب رخصة بناء', cardBuildStatus: 'قيد المعالجة',
    cardBuildKv1: 'رقم الطلب', cardBuildKv2: 'المدة المتوقعة',
    cardBuildFoot1: 'تم التقديم ١٢ محرم ١٤٤٧هـ', cardBuildFoot2: 'الخطوة ٣ من ٥',
    cardBillTitle: 'دفع فاتورة', cardBillText: 'فاتورة خدمات شهر محرّم',
    cardPay: 'سدد الآن', cardMsg: 'ردّت البلدية على شكواك', cardMsgTime: 'منذ ١٢ دقيقة',
    // Quick
    quickTitle: 'ابدأ من هنا', quickLede: 'أكثر الخدمات استخدامًا متاحة بنقرة واحدة',
    // About
    aboutEyebrow: 'عن البلدية', aboutTitle: 'نعمل لخدمتكم وتطوير مدينتكم',
    aboutP1: 'بلدية النخيل هي الجهة الحكومية المسؤولة عن إدارة الشؤون البلدية في نطاق النخيل والأحياء التابعة لها. نعمل على تطوير البنية التحتية، الحفاظ على البيئة، تنظيم النشاط العمراني، وتقديم خدمات نوعية للمقيمين والمستثمرين.',
    aboutP2: 'نلتزم برؤية المملكة ٢٠٣٠ في تحقيق التحول الرقمي، وتسهيل الوصول إلى الخدمات الحكومية بأعلى معايير الجودة والشفافية.',
    kpi1v: '٢٥٠ ألف', kpi1l: 'نسمة مستفيدة',
    kpi2v: '١٢ حيًّا', kpi2l: 'في النطاق البلدي',
    kpi3v: '١٥٠٠ كم²', kpi3l: 'مساحة إجمالية',
    kpi4v: '٤.٧/٥', kpi4l: 'تقييم رضا المستفيدين',
    aboutCaption: 'مقر البلدية الرئيسي — حي النخيل',
    pillar1t: 'التطوير العمراني', pillar1d: 'تخطيط وتنظيم المدن والأحياء',
    pillar2t: 'الخدمات العامة', pillar2d: 'نظافة، إنارة، حدائق، طرق',
    pillar3t: 'التراخيص', pillar3d: 'بناء، مهن، أنشطة تجارية',
    pillar4t: 'الرقابة', pillar4d: 'السلامة، الغذاء، الأسواق',
    // Services
    srvEyebrow: 'دليل الخدمات', srvTitle: 'خدماتنا الإلكترونية',
    srvLede: '٤٢ خدمة متاحة على مدار الساعة. اختر القسم المناسب',
    fAll: 'الكل', fBuild: 'البناء والتخطيط', fBiz: 'التراخيص التجارية',
    fHealth: 'الصحة والسلامة', fComp: 'الشكاوى والملاحظات', fPay: 'المدفوعات',
    // News
    newsEyebrow: 'المركز الإعلامي', newsTitle: 'آخر الأخبار والإعلانات', newsAll: 'جميع الأخبار ←',
    // Counters
    c1v: 'طلب منجز هذا العام', c2v: 'خدمة إلكترونية', c3v: '٪ نسبة رضا المستفيدين', c4v: 'حيًّا تحت الخدمة',
    // Contact
    contactEyebrow: 'تواصل معنا', contactTitle: 'نحن هنا لخدمتك',
    contactP: 'فريق خدمة المستفيدين متاح على مدار الساعة للإجابة على استفساراتكم واستقبال ملاحظاتكم.',
    contactLoc: 'المقر الرئيسي', contactLocV: 'حي النخيل، طريق الملك فهد، مبنى البلدية',
    contactTel: 'الرقم الموحد', contactTelV: '+966 11 234 5678',
    contactMail: 'البريد الإلكتروني', contactMailV: 'info@nakheel.gov.sa',
    contactHours: 'ساعات العمل', contactHoursV: 'الأحد - الخميس · ٨ صباحًا - ٤ مساءً',
    contactFormTitle: 'أرسل رسالة',
    fieldName: 'الاسم الكامل', fieldPhone: 'رقم الجوال', fieldEmail: 'البريد الإلكتروني',
    fieldType: 'نوع الطلب', fieldMsg: 'الرسالة', fieldPick: 'اختر نوع الطلب',
    typeInquiry: 'استفسار', typeComplaint: 'شكوى', typeSuggest: 'اقتراح', typeRequest: 'طلب خدمة',
    phName: 'أدخل اسمك', phPhone: '05XXXXXXXX', phEmail: 'you@example.com',
    phMsg: 'اكتب رسالتك هنا...', sendBtn: 'إرسال الرسالة', sentBtn: 'تم الإرسال ✓',
    // Footer
    footerBrandP: 'الجهة الرسمية المسؤولة عن إدارة الشؤون البلدية في نطاق النخيل والأحياء التابعة لها.',
    footerLinksTitle: 'روابط سريعة',
    footerEservicesTitle: 'الخدمات الإلكترونية',
    footerContactTitle: 'تواصل',
    footerCR: '© ٢٠٢٦ بلدية النخيل. جميع الحقوق محفوظة.',
    footPrivacy: 'سياسة الخصوصية', footTerms: 'الشروط والأحكام', footSitemap: 'خريطة الموقع',
    footSrv1: 'رخصة بناء', footSrv2: 'ترخيص نشاط تجاري', footSrv3: 'شهادة صحية',
    footSrv4: 'دفع الفواتير', footSrv5: 'تقديم شكوى',
    // User sidebar
    userOverview: 'نظرة عامة', userNewRequest: 'طلب خدمة جديدة', userMyRequests: 'طلباتي',
    userBills: 'المدفوعات والفواتير', userComplaints: 'الشكاوى والملاحظات',
    userNotifications: 'الإشعارات', userProfile: 'الملف الشخصي',
    userPageTitle: 'نظرة عامة', userPageSub: 'مرحبًا بعودتك، عبد الرحمن',
    // Admin sidebar
    adminDash: 'لوحة المعلومات', adminRequests: 'الطلبات', adminServices: 'إدارة الخدمات',
    adminNews: 'إدارة الأخبار', adminComplaints: 'الشكاوى',
    adminUsers: 'المستخدمون', adminFinance: 'المالية', adminSettings: 'الإعدادات',
    adminPageTitle: 'لوحة المعلومات', adminPageSub: 'مرحبًا، م. خالد — مدير النظام',
    // Common dashboard
    search: 'بحث', newNotif: 'إشعار جديد',
    pending: 'قيد الانتظار', inProgress: 'قيد المعالجة', done: 'منجزة',
    rejected: 'مرفوضة', draft: 'مسودة', replied: 'تم الرد', resolved: 'تم الحل',
    // User overview
    uoOpenV: '٣', uoOpenL: 'طلبات مفتوحة',
    uoDoneV: '١٢', uoDoneL: 'طلبات منجزة',
    uoBillsV: '٦٠٠ ر.س', uoBillsL: 'مستحقات هذا الشهر',
    uoNotifV: '٢', uoNotifL: 'إشعارات غير مقروءة',
    uoQuick: 'إجراءات سريعة', uoRecent: 'آخر طلباتي', uoBills: 'الفواتير المستحقة',
    uoNews: 'أحدث الإعلانات',
    uaNew: 'طلب جديد', uaTrack: 'متابعة طلب', uaPay: 'دفع فاتورة', uaComplaint: 'تقديم شكوى',
    viewAll: 'عرض الكل', payNow: 'سدد الآن',
    noItems: 'لا توجد عناصر',
    // New request page
    nrTitle: 'طلب خدمة جديدة', nrSub: 'اختر الخدمة واملأ التفاصيل',
    nrPick: 'اختر الخدمة', nrDetails: 'تفاصيل الطلب', nrDesc: 'وصف الطلب',
    nrAttach: 'المرفقات', nrUpload: 'اضغط لرفع الملفات أو اسحبها هنا',
    nrSubmit: 'إرسال الطلب', nrSent: 'تم استلام طلبك ✓',
    phDesc: 'اشرح طبيعة طلبك بالتفصيل...',
    // Requests page
    rqTitle: 'طلباتي', rqSub: 'جميع الطلبات التي قدمتها ومتابعتها',
    tabAll: 'الكل', tabOpen: 'مفتوحة', tabDone: 'منجزة', tabRejected: 'مرفوضة',
    colId: 'الرقم', colType: 'الخدمة', colDate: 'التاريخ', colStatus: 'الحالة', colCost: 'الرسوم', colActions: 'إجراءات',
    rowView: 'عرض', rowTrack: 'متابعة', rowPay: 'دفع',
    // Bills page
    blTitle: 'المدفوعات والفواتير', blSub: 'جميع الفواتير وحالة السداد',
    blPending: 'مستحقة', blPaid: 'مدفوعة', blAmount: 'المبلغ', blDue: 'الاستحقاق', blInv: 'الفاتورة',
    // Complaints page
    cpTitle: 'الشكاوى والملاحظات', cpSub: 'تابع شكاواك وملاحظاتك المقدمة للبلدية',
    newComplaint: 'شكوى جديدة', cpSubject: 'الموضوع', cpDate: 'التاريخ', cpStatus: 'الحالة',
    // Notifications
    ntTitle: 'الإشعارات', ntSub: 'كل التحديثات والتنبيهات',
    markAllRead: 'تعليم الكل كمقروء',
    // Profile
    prTitle: 'الملف الشخصي', prSub: 'معلوماتك الشخصية وإعدادات الحساب',
    prPersonal: 'البيانات الشخصية', prContact: 'بيانات الاتصال', prAddress: 'العنوان',
    prName: 'الاسم', prId: 'رقم الهوية', prPhone: 'الجوال', prEmail: 'البريد',
    prDistrict: 'الحي', prStreet: 'الشارع', prBuilding: 'رقم المبنى',
    prSave: 'حفظ التغييرات', prSaved: 'تم الحفظ ✓',
    // Admin overview
    aoPendingV: '١٢', aoPendingL: 'طلبات جديدة',
    aoProgressV: '٢٤', aoProgressL: 'قيد المعالجة',
    aoDoneV: '١٢٤٨', aoDoneL: 'منجزة هذا الشهر',
    aoRevenueV: '٢٫٠٥م', aoRevenueL: 'إيرادات الشهر (ر.س)',
    aoTrend: 'تطور الطلبات (آخر ٦ أشهر)', aoBreakdown: 'توزيع حالات الطلبات',
    aoRecent: 'أحدث الطلبات', aoByDist: 'حسب الحي',
    sDone: 'منجزة', sProg: 'قيد المعالجة', sPend: 'قيد الانتظار', sRej: 'مرفوضة',
    // Admin requests
    arqTitle: 'إدارة الطلبات', arqSub: 'مراجعة وتحديث ومعالجة طلبات المستفيدين',
    colCitizen: 'المستفيد', colDistrict: 'الحي', colPriority: 'الأولوية',
    priHigh: 'عالية', priNormal: 'متوسطة', priLow: 'منخفضة',
    rowApprove: 'قبول', rowReject: 'رفض', rowMore: 'المزيد',
    // Admin services
    asvTitle: 'إدارة الخدمات', asvSub: 'إضافة وتعديل وإيقاف الخدمات الإلكترونية',
    addService: 'إضافة خدمة', asvColName: 'الخدمة', asvColCat: 'الفئة',
    asvColFee: 'الرسوم', asvColSla: 'مدة التنفيذ (أيام)', asvColUse: 'عدد الاستخدامات', asvColActive: 'مفعّلة',
    toggleOn: 'مفعّل', toggleOff: 'متوقف', rowEdit: 'تعديل', rowDel: 'حذف',
    // Admin news
    anwTitle: 'إدارة الأخبار', anwSub: 'نشر وتعديل الأخبار والإعلانات',
    addNews: 'خبر جديد', nwColTitle: 'العنوان', nwColCat: 'الفئة', nwColDate: 'التاريخ', nwColStatus: 'الحالة',
    pub: 'منشور', draft2: 'مسودة',
    // Admin complaints
    acpTitle: 'إدارة الشكاوى', acpSub: 'مراجعة والرد على شكاوى المواطنين',
    // Admin users
    ausTitle: 'المستخدمون', ausSub: 'إدارة حسابات المواطنين والمستخدمين',
    colName: 'الاسم', colIdNo: 'رقم الهوية', colPhone: 'الجوال', colReq: 'الطلبات', colJoined: 'تاريخ الانضمام',
    addUser: 'إضافة مستخدم',
    // Admin finance
    afnTitle: 'المالية', afnSub: 'الإيرادات والمدفوعات والمستحقات',
    fnMonth: 'إيرادات الشهر الحالي', fnLast: 'الشهر الماضي', fnPending: 'مستحقات', fnYear: 'إجمالي السنة',
    fnTrend: 'الإيرادات الشهرية',
    // Admin settings
    astTitle: 'الإعدادات', astSub: 'إعدادات النظام والمظهر والإشعارات',
    astGen: 'إعدادات عامة', astNotif: 'إعدادات الإشعارات', astA11y: 'إمكانية الوصول',
    astSiteName: 'اسم الموقع', astEmail: 'البريد الرسمي', astLang: 'لغة النظام الافتراضية',
    astEmailNew: 'إشعار عند طلب جديد', astEmailDone: 'إشعار عند إنجاز طلب', astSmsDone: 'رسالة SMS عند السداد',
    save: 'حفظ',
    // Toast
    toastSent: 'تم إرسال رسالتك بنجاح',
    toastSaved: 'تم الحفظ',
    toastSubmitted: 'تم تقديم الطلب',
    toastPaid: 'تمت عملية الدفع بنجاح',
    toastAdded: 'تمت الإضافة بنجاح',
    toastUpdated: 'تم التحديث بنجاح',
    toastError: 'حدث خطأ، حاول مرة أخرى',
    // Misc
    required: 'مطلوب',
    comingSoon: 'قريبًا',
  },
  en: {
    brandName: 'Al-Nakheel Municipality',
    brandSub:  'Ministry of Municipalities & Housing',
    topAbout: 'About', topNews: 'News', topContact: 'Contact', topA11y: 'Accessibility',
    userPortal: 'Citizen Portal', adminPortal: 'Admin Portal',
    navHome: 'Home', navAbout: 'About', navServices: 'Services',
    navNews: 'Newsroom', navContact: 'Contact',
    navCta: 'E-Services', backToSite: '← Back to site',
    heroBadge: 'Municipal Services Platform',
    heroTitle: 'Serving you around the clock,<br/>in the simplest way',
    heroLede: 'A unified platform for all Al-Nakheel Municipality services. Complete your transactions, track your requests, and pay your fees online — easily and securely, from anywhere at any time.',
    heroCta1: 'Start service', heroCta2: 'Explore services',
    stat1v: '42', stat1l: 'E-services',
    stat2v: '98%', stat2l: 'Completion rate',
    stat3v: '24/7', stat3l: 'Always available',
    cardBuildTitle: 'Building permit', cardBuildStatus: 'In progress',
    cardBuildKv1: 'Request #', cardBuildKv2: 'Expected duration',
    cardBuildFoot1: 'Submitted 12 Muharram 1447 AH', cardBuildFoot2: 'Step 3 of 5',
    cardBillTitle: 'Pay bill', cardBillText: 'Service bill — Muharram',
    cardPay: 'Pay now', cardMsg: 'Municipality replied to your complaint', cardMsgTime: '12 min ago',
    quickTitle: 'Start here', quickLede: 'Most-used services available in one click',
    aboutEyebrow: 'About', aboutTitle: 'Working to serve you and develop your city',
    aboutP1: 'Al-Nakheel Municipality is the government body responsible for managing municipal affairs across the Nakheel district and its neighborhoods. We develop infrastructure, protect the environment, organize urban activity, and provide quality services to residents and investors.',
    aboutP2: 'We are committed to Saudi Vision 2030 in achieving digital transformation and facilitating access to government services with the highest standards of quality and transparency.',
    kpi1v: '250K', kpi1l: 'People served',
    kpi2v: '12', kpi2l: 'Neighborhoods',
    kpi3v: '1,500 km²', kpi3l: 'Total area',
    kpi4v: '4.7/5', kpi4l: 'Satisfaction rating',
    aboutCaption: 'Main HQ — Al-Nakheel District',
    pillar1t: 'Urban development', pillar1d: 'City planning & zoning',
    pillar2t: 'Public services', pillar2d: 'Cleaning, lighting, parks, roads',
    pillar3t: 'Licensing', pillar3d: 'Building, trades, business',
    pillar4t: 'Inspection', pillar4d: 'Safety, food, markets',
    srvEyebrow: 'Service catalog', srvTitle: 'Our e-services',
    srvLede: '42 services available 24/7. Pick a category',
    fAll: 'All', fBuild: 'Building & planning', fBiz: 'Business licenses',
    fHealth: 'Health & safety', fComp: 'Complaints', fPay: 'Payments',
    newsEyebrow: 'Newsroom', newsTitle: 'Latest news & announcements', newsAll: 'All news →',
    c1v: 'Requests this year', c2v: 'E-services', c3v: '% satisfaction', c4v: 'Neighborhoods',
    contactEyebrow: 'Contact us', contactTitle: "We're here to help",
    contactP: 'Our beneficiary service team is available 24/7 to answer your questions and receive your feedback.',
    contactLoc: 'Main HQ', contactLocV: 'Nakheel District, King Fahd Road',
    contactTel: 'Hotline', contactTelV: '+966 11 234 5678',
    contactMail: 'Email', contactMailV: 'info@nakheel.gov.sa',
    contactHours: 'Hours', contactHoursV: 'Sun – Thu · 8:00 AM – 4:00 PM',
    contactFormTitle: 'Send a message',
    fieldName: 'Full name', fieldPhone: 'Mobile', fieldEmail: 'Email',
    fieldType: 'Request type', fieldMsg: 'Message', fieldPick: 'Pick a type',
    typeInquiry: 'Inquiry', typeComplaint: 'Complaint', typeSuggest: 'Suggestion', typeRequest: 'Service request',
    phName: 'Enter your name', phPhone: '05XXXXXXXX', phEmail: 'you@example.com',
    phMsg: 'Write your message...', sendBtn: 'Send message', sentBtn: 'Sent ✓',
    footerBrandP: 'The official body responsible for managing municipal affairs across the Nakheel district and its neighborhoods.',
    footerLinksTitle: 'Quick links',
    footerEservicesTitle: 'E-services',
    footerContactTitle: 'Contact',
    footerCR: '© 2026 Al-Nakheel Municipality. All rights reserved.',
    footPrivacy: 'Privacy', footTerms: 'Terms', footSitemap: 'Sitemap',
    footSrv1: 'Building permit', footSrv2: 'Business license', footSrv3: 'Health certificate',
    footSrv4: 'Pay bills', footSrv5: 'Submit complaint',
    userOverview: 'Overview', userNewRequest: 'New service request', userMyRequests: 'My requests',
    userBills: 'Bills & payments', userComplaints: 'Complaints & feedback',
    userNotifications: 'Notifications', userProfile: 'Profile',
    userPageTitle: 'Overview', userPageSub: 'Welcome back, Abdulrahman',
    adminDash: 'Dashboard', adminRequests: 'Requests', adminServices: 'Services',
    adminNews: 'News', adminComplaints: 'Complaints',
    adminUsers: 'Users', adminFinance: 'Finance', adminSettings: 'Settings',
    adminPageTitle: 'Dashboard', adminPageSub: 'Welcome, Eng. Khaled — System admin',
    search: 'Search', newNotif: 'New notification',
    pending: 'Pending', inProgress: 'In progress', done: 'Completed',
    rejected: 'Rejected', draft: 'Draft', replied: 'Replied', resolved: 'Resolved',
    uoOpenV: '3', uoOpenL: 'Open requests',
    uoDoneV: '12', uoDoneL: 'Completed',
    uoBillsV: '600 SAR', uoBillsL: 'Due this month',
    uoNotifV: '2', uoNotifL: 'Unread notifications',
    uoQuick: 'Quick actions', uoRecent: 'Recent requests', uoBills: 'Pending bills',
    uoNews: 'Latest announcements',
    uaNew: 'New request', uaTrack: 'Track request', uaPay: 'Pay bill', uaComplaint: 'Submit complaint',
    viewAll: 'View all', payNow: 'Pay now',
    noItems: 'No items',
    nrTitle: 'New service request', nrSub: 'Pick a service and fill in the details',
    nrPick: 'Choose service', nrDetails: 'Request details', nrDesc: 'Description',
    nrAttach: 'Attachments', nrUpload: 'Click or drop files here',
    nrSubmit: 'Submit request', nrSent: 'Request received ✓',
    phDesc: 'Describe your request in detail...',
    rqTitle: 'My requests', rqSub: 'All your submitted requests and their status',
    tabAll: 'All', tabOpen: 'Open', tabDone: 'Completed', tabRejected: 'Rejected',
    colId: 'ID', colType: 'Service', colDate: 'Date', colStatus: 'Status', colCost: 'Fee', colActions: 'Actions',
    rowView: 'View', rowTrack: 'Track', rowPay: 'Pay',
    blTitle: 'Bills & payments', blSub: 'All your bills and payment status',
    blPending: 'Due', blPaid: 'Paid', blAmount: 'Amount', blDue: 'Due date', blInv: 'Invoice',
    cpTitle: 'Complaints & feedback', cpSub: 'Track the complaints you submitted to the municipality',
    newComplaint: 'New complaint', cpSubject: 'Subject', cpDate: 'Date', cpStatus: 'Status',
    ntTitle: 'Notifications', ntSub: 'All updates and alerts',
    markAllRead: 'Mark all as read',
    prTitle: 'Profile', prSub: 'Your personal info and account settings',
    prPersonal: 'Personal info', prContact: 'Contact info', prAddress: 'Address',
    prName: 'Name', prId: 'ID number', prPhone: 'Mobile', prEmail: 'Email',
    prDistrict: 'District', prStreet: 'Street', prBuilding: 'Building #',
    prSave: 'Save changes', prSaved: 'Saved ✓',
    aoPendingV: '12', aoPendingL: 'New requests',
    aoProgressV: '24', aoProgressL: 'In progress',
    aoDoneV: '1,248', aoDoneL: 'Completed this month',
    aoRevenueV: '2.05M', aoRevenueL: 'Monthly revenue (SAR)',
    aoTrend: 'Requests trend (last 6 months)', aoBreakdown: 'Request status breakdown',
    aoRecent: 'Recent requests', aoByDist: 'By district',
    sDone: 'Done', sProg: 'In progress', sPend: 'Pending', sRej: 'Rejected',
    arqTitle: 'Requests management', arqSub: 'Review, update and process citizen requests',
    colCitizen: 'Citizen', colDistrict: 'District', colPriority: 'Priority',
    priHigh: 'High', priNormal: 'Normal', priLow: 'Low',
    rowApprove: 'Approve', rowReject: 'Reject', rowMore: 'More',
    asvTitle: 'Services management', asvSub: 'Add, edit and pause e-services',
    addService: 'Add service', asvColName: 'Service', asvColCat: 'Category',
    asvColFee: 'Fee', asvColSla: 'SLA (days)', asvColUse: 'Usage', asvColActive: 'Active',
    toggleOn: 'Active', toggleOff: 'Paused', rowEdit: 'Edit', rowDel: 'Delete',
    anwTitle: 'News management', anwSub: 'Publish and edit news & announcements',
    addNews: 'New article', nwColTitle: 'Title', nwColCat: 'Category', nwColDate: 'Date', nwColStatus: 'Status',
    pub: 'Published', draft2: 'Draft',
    acpTitle: 'Complaints management', acpSub: 'Review and respond to citizen complaints',
    ausTitle: 'Users', ausSub: 'Manage citizen accounts and users',
    colName: 'Name', colIdNo: 'ID number', colPhone: 'Mobile', colReq: 'Requests', colJoined: 'Joined',
    addUser: 'Add user',
    afnTitle: 'Finance', afnSub: 'Revenue, payments and outstanding balances',
    fnMonth: 'This month revenue', fnLast: 'Last month', fnPending: 'Outstanding', fnYear: 'Year to date',
    fnTrend: 'Monthly revenue',
    astTitle: 'Settings', astSub: 'System, appearance and notification preferences',
    astGen: 'General', astNotif: 'Notifications', astA11y: 'Accessibility',
    astSiteName: 'Site name', astEmail: 'Official email', astLang: 'Default language',
    astEmailNew: 'Email on new request', astEmailDone: 'Email on completion', astSmsDone: 'SMS on payment',
    save: 'Save',
    toastSent: 'Message sent successfully',
    toastSaved: 'Saved',
    toastSubmitted: 'Request submitted',
    toastPaid: 'Payment successful',
    toastAdded: 'Added successfully',
    toastUpdated: 'Updated successfully',
    toastError: 'Something went wrong, please try again',
    comingSoon: 'Coming soon',
  },
};

/* Category labels per language */
window.CAT_LABEL = {
  ar: { build: 'البناء', business: 'تجاري', health: 'صحة', complaint: 'شكاوى', pay: 'مدفوعات' },
  en: { build: 'Building', business: 'Business', health: 'Health', complaint: 'Complaints', pay: 'Payments' },
};

/* News category labels per language */
window.NEWS_CAT = {
  ar: { 'إعلان': 'إعلان', 'فعاليات': 'فعاليات', 'تطوير': 'تطوير', 'صحة': 'صحة', 'تعميم': 'تعميم' },
  en: { 'إعلان': 'Announcement', 'فعاليات': 'Events', 'تطوير': 'Development', 'صحة': 'Health', 'تعميم': 'Circular' },
};

/* =====================================================================
   Bilingual data
   ===================================================================== */

window.SITE = {
  ar: {
    quickServices: [
      { icon: '🏗️', title: 'رخصة بناء', desc: 'إصدار وتجديد رخص البناء', color: '#e8f3f0', tint: '#0e6b53', cat: 'build', action: 'svc-build' },
      { icon: '🏪', title: 'ترخيص نشاط تجاري', desc: 'فتح أو تجديد محل تجاري', color: '#fdf5e3', tint: '#a07a0c', cat: 'business', action: 'svc-biz' },
      { icon: '📋', title: 'شهادة صحية', desc: 'للعاملين في الأغذية', color: '#eaf4f8', tint: '#1e6b85', cat: 'health', action: 'svc-health' },
      { icon: '💳', title: 'دفع فاتورة', desc: 'رسوم بلدية وخدمات', color: '#f0eaf6', tint: '#5e3b8a', cat: 'pay', action: 'svc-pay' },
      { icon: '📢', title: 'تقديم شكوى', desc: 'ملاحظاتك تهمنا', color: '#fbeae8', tint: '#c0413a', cat: 'complaint', action: 'svc-complaint' },
      { icon: '📑', title: 'طلب وثيقة', desc: 'إفادة، تعريف، صورة طبق الأصل', color: '#e6f5ee', tint: '#2f9c6f', cat: 'build', action: 'svc-doc' },
      { icon: '🅿️', title: 'اشتراك موقف', desc: 'حجز موقف شهري', color: '#fcf0d8', tint: '#c98014', cat: 'pay', action: 'svc-park' },
      { icon: '🔍', title: 'متابعة طلب', desc: 'تتبع حالة طلب سابق', color: '#e3f1ea', tint: '#1c8159', cat: 'build', action: 'svc-track' },
    ],
    services: [
      { id: 'build-1', cat: 'build', icon: '🏗️', title: 'إصدار رخصة بناء', desc: 'طلب رخصة بناء جديدة لقطعة أرض سكنية أو تجارية', price: 1200, sla: '14 يوم', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'build-2', cat: 'build', icon: '📐', title: 'تجديد رخصة بناء', desc: 'تمديد رخصة بناء قائمة لمدة إضافية', price: 600, sla: '7 أيام', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'build-3', cat: 'build', icon: '🏘️', title: 'شهادة إتمام بناء', desc: 'إصدار شهادة إتمام بناء للمبنى الجاهز', price: 400, sla: '5 أيام', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'biz-1', cat: 'business', icon: '🏪', title: 'ترخيص محل تجاري', desc: 'فتح محل تجاري جديد داخل النطاق البلدي', price: 800, sla: '10 أيام', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'biz-2', cat: 'business', icon: '♻️', title: 'تجديد رخصة نشاط', desc: 'تجديد رخصة نشاط قائم لمدة سنة', price: 500, sla: '5 أيام', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'biz-3', cat: 'business', icon: '🍽️', title: 'ترخيص مطعم/مقهى', desc: 'ترخيص مطعم أو مقهى وفق اشتراطات الصحة والسلامة', price: 1500, sla: '14 يوم', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'health-1', cat: 'health', icon: '🩺', title: 'شهادة صحية', desc: 'شهادة صحية للعاملين في مجال الأغذية', price: 100, sla: '3 أيام', color: '#eaf4f8', tint: '#1e6b85' },
      { id: 'health-2', cat: 'health', icon: '🛡️', title: 'شهادة سلامة', desc: 'فحص سلامة مبنى أو منشأة تجارية', price: 350, sla: '7 أيام', color: '#eaf4f8', tint: '#1e6b85' },
      { id: 'comp-1', cat: 'complaint', icon: '🚧', title: 'البلاغ عن مخالفة بناء', desc: 'الإبلاغ عن بناء مخالف أو تعدي على أملاك الدولة', price: 0, sla: 'فوري', color: '#fbeae8', tint: '#c0413a' },
      { id: 'comp-2', cat: 'complaint', icon: '💡', title: 'الإبلاغ عن عطل', desc: 'عطل إنارة طريق، حاوية، أو مرفق عام', price: 0, sla: 'فوري', color: '#fbeae8', tint: '#c0413a' },
      { id: 'pay-1', cat: 'pay', icon: '💧', title: 'دفع رسوم خدمات', desc: 'سداد رسوم النظافة والإنارة والخدمات العامة', price: 0, sla: 'فوري', color: '#f0eaf6', tint: '#5e3b8a' },
      { id: 'pay-2', cat: 'pay', icon: '🅿️', title: 'اشتراك موقف', desc: 'حجز موقف شهري قريب من المنزل أو العمل', price: 250, sla: 'فوري', color: '#f0eaf6', tint: '#5e3b8a' },
    ],
    news: [
      { id: 'n1', date: '١٥ محرم ١٤٤٧', cat: 'إعلان', title: 'إطلاق خدمة تجديد رخص البناء إلكترونيًا بالكامل', excerpt: 'أعلنت بلدية النخيل عن إتاحة تجديد رخص البناء عبر البوابة الإلكترونية، دون الحاجة لزيارة مقر البلدية، في إطار التحول الرقمي.', img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1200&q=80', hero: true },
      { id: 'n2', date: '١٢ محرم ١٤٤٧', cat: 'فعاليات', title: 'افتتاح حديقة النخيل المركزية', img: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&w=800&q=80' },
      { id: 'n3', date: '١٠ محرم ١٤٤٧', cat: 'تطوير', title: 'بدء أعمال تطوير طريق الملك فهد', img: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80' },
      { id: 'n4', date: '٧ محرم ١٤٤٧', cat: 'صحة', title: 'حملة تفتيش على المطاعم والمقاهي', img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80' },
      { id: 'n5', date: '٥ محرم ١٤٤٧', cat: 'تعميم', title: 'تحديث اشتراطات البناء الجديدة', img: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80' },
    ],
    userRequests: [
      { id: 'R-2026-08921', type: 'رخصة بناء', status: 'progress', progress: 64, date: '١٢ محرم ١٤٤٧', cost: 1200, priority: 'high' },
      { id: 'R-2026-08874', type: 'ترخيص نشاط تجاري', status: 'pending', progress: 25, date: '١٠ محرم ١٤٤٧', cost: 800, priority: 'normal' },
      { id: 'R-2026-08820', type: 'شهادة صحية', status: 'done', progress: 100, date: '٢ محرم ١٤٤٧', cost: 100, priority: 'normal' },
      { id: 'R-2026-08755', type: 'دفع رسوم خدمات', status: 'done', progress: 100, date: '٢٨ صفر ١٤٤٦', cost: 350, priority: 'low' },
    ],
    bills: [
      { id: 'B-2026-0114', type: 'رسوم خدمات شهر محرّم', amount: 350, due: '٢٠ محرم ١٤٤٧', status: 'pending' },
      { id: 'B-2026-0113', type: 'اشتراك موقف - يناير', amount: 250, due: '١٥ محرم ١٤٤٧', status: 'pending' },
      { id: 'B-2026-0112', type: 'رسوم خدمات شهر صفر', amount: 350, due: 'مدفوعة', status: 'paid' },
    ],
    complaints: [
      { id: 'C-2026-0331', subject: 'عطل إنارة في شارع الأمير سلطان', status: 'replied', date: '١١ محرم ١٤٤٧' },
      { id: 'C-2026-0320', subject: 'تجمع نفايات في حي الياسمين', status: 'in-progress', date: '٥ محرم ١٤٤٧' },
      { id: 'C-2026-0305', subject: 'حفرة في الطريق أمام مدرسة الفهد', status: 'resolved', date: '٢٢ صفر ١٤٤٦' },
    ],
    notifications: [
      { id: 'nt1', type: 'request', text: 'تم تحديث حالة طلب رخصة البناء إلى "قيد المعالجة"', time: 'منذ ١٢ دقيقة', unread: true },
      { id: 'nt2', type: 'bill', text: 'فاتورة جديدة مستحقة بقيمة ٣٥٠ ر.س', time: 'منذ ٣ ساعات', unread: true },
      { id: 'nt3', type: 'reply', text: 'ردّت البلدية على شكواك بخصوص إنارة الشارع', time: 'أمس', unread: false },
      { id: 'nt4', type: 'news', text: 'خبر جديد: إطلاق خدمة تجديد رخص البناء إلكترونيًا', time: 'منذ يومين', unread: false },
    ],
    adminRequests: [
      { id: 'R-2026-08921', user: 'عبد الرحمن العتيبي', userId: '1098765432', type: 'رخصة بناء', date: '١٢ محرم', status: 'progress', priority: 'high', district: 'حي النخيل' },
      { id: 'R-2026-08920', user: 'محمد القحطاني', userId: '1087654321', type: 'ترخيص نشاط', date: '١٢ محرم', status: 'pending', priority: 'normal', district: 'حي الياسمين' },
      { id: 'R-2026-08919', user: 'فاطمة الزهراني', userId: '1076543210', type: 'شهادة صحية', date: '١١ محرم', status: 'pending', priority: 'normal', district: 'حي الورود' },
      { id: 'R-2026-08918', user: 'سعيد الغامدي', userId: '1065432109', type: 'بناء', date: '١١ محرم', status: 'progress', priority: 'high', district: 'حي الفيصلية' },
      { id: 'R-2026-08917', user: 'نورة الدوسري', userId: '1054321098', type: 'تجديد رخصة', date: '١٠ محرم', status: 'done', priority: 'low', district: 'حي النخيل' },
      { id: 'R-2026-08916', user: 'خالد الشمري', userId: '1043210987', type: 'شهادة سلامة', date: '١٠ محرم', status: 'progress', priority: 'normal', district: 'حي الملقا' },
      { id: 'R-2026-08915', user: 'هند المالكي', userId: '1032109876', type: 'رخصة بناء', date: '٩ محرم', status: 'rejected', priority: 'normal', district: 'حي العقيق' },
      { id: 'R-2026-08914', user: 'أحمد العمري', userId: '1021098765', type: 'ترخيص مطعم', date: '٩ محرم', status: 'pending', priority: 'high', district: 'حي النزهة' },
      { id: 'R-2026-08913', user: 'لينا الحربي', userId: '1010987654', type: 'دفع رسوم', date: '٨ محرم', status: 'done', priority: 'low', district: 'حي النخيل' },
      { id: 'R-2026-08912', user: 'يوسف القرني', userId: '1009876543', type: 'بناء', date: '٨ محرم', status: 'progress', priority: 'normal', district: 'حي الياسمين' },
      { id: 'R-2026-08911', user: 'ريم البلوي', userId: '1098765430', type: 'اشتراك موقف', date: '٧ محرم', status: 'done', priority: 'low', district: 'حي الورود' },
      { id: 'R-2026-08910', user: 'بدر الجهني', userId: '1087654320', type: 'شهادة صحية', date: '٧ محرم', status: 'progress', priority: 'normal', district: 'حي الفيصلية' },
    ],
    adminServices: [
      { id: 's1', name: 'إصدار رخصة بناء', cat: 'build', fee: 1200, sla: '14', active: true, count: 1245 },
      { id: 's2', name: 'تجديد رخصة بناء', cat: 'build', fee: 600, sla: '7', active: true, count: 832 },
      { id: 's3', name: 'ترخيص محل تجاري', cat: 'business', fee: 800, sla: '10', active: true, count: 654 },
      { id: 's4', name: 'تجديد رخصة نشاط', cat: 'business', fee: 500, sla: '5', active: true, count: 1208 },
      { id: 's5', name: 'شهادة صحية', cat: 'health', fee: 100, sla: '3', active: true, count: 2890 },
      { id: 's6', name: 'شهادة سلامة', cat: 'health', fee: 350, sla: '7', active: true, count: 412 },
      { id: 's7', name: 'اشتراك موقف', cat: 'pay', fee: 250, sla: '1', active: true, count: 1850 },
      { id: 's8', name: 'دفع رسوم خدمات', cat: 'pay', fee: 0, sla: '0', active: true, count: 5621 },
      { id: 's9', name: 'البلاغ عن مخالفة بناء', cat: 'complaint', fee: 0, sla: '1', active: true, count: 187 },
      { id: 's10', name: 'الإبلاغ عن عطل', cat: 'complaint', fee: 0, sla: '1', active: false, count: 92 },
    ],
    adminComplaints: [
      { id: 'C-2026-0331', user: 'أحمد العمري', subject: 'عطل إنارة في شارع الأمير سلطان', district: 'حي النزهة', date: '١١ محرم', status: 'pending' },
      { id: 'C-2026-0330', user: 'سارة السبيعي', subject: 'تسرب مياه في الحديقة العامة', district: 'حي الورود', date: '١١ محرم', status: 'pending' },
      { id: 'C-2026-0329', user: 'ماجد الرشيدي', subject: 'تجمع نفايات خلف المجمع', district: 'حي الياسمين', date: '١٠ محرم', status: 'progress' },
      { id: 'C-2026-0328', user: 'نوال العتيبي', subject: 'ضوضاء ورشة بناء', district: 'حي الفيصلية', date: '١٠ محرم', status: 'progress' },
      { id: 'C-2026-0327', user: 'فهد الحربي', subject: 'حفرة عميقة في الطريق', district: 'حي الملقا', date: '٩ محرم', status: 'pending' },
      { id: 'C-2026-0326', user: 'أمل القرشي', subject: 'توقف حاويات النظافة', district: 'حي النخيل', date: '٨ محرم', status: 'resolved' },
      { id: 'C-2026-0325', user: 'سلطان الزايدي', subject: 'إهمال صيانة الحديقة', district: 'حي العقيق', date: '٧ محرم', status: 'resolved' },
    ],
    adminUsers: [
      { id: 'u1', name: 'عبد الرحمن العتيبي', id_no: '1098765432', phone: '0501234567', district: 'حي النخيل', requests: 8, joined: '١٤٤٥/٠٣/١٢' },
      { id: 'u2', name: 'محمد القحطاني', id_no: '1087654321', phone: '0509876543', district: 'حي الياسمين', requests: 4, joined: '١٤٤٦/٠١/٢٠' },
      { id: 'u3', name: 'فاطمة الزهراني', id_no: '1076543210', phone: '0551122334', district: 'حي الورود', requests: 12, joined: '١٤٤٤/١١/٠٥' },
      { id: 'u4', name: 'سعيد الغامدي', id_no: '1065432109', phone: '0533445566', district: 'حي الفيصلية', requests: 2, joined: '١٤٤٦/٠٢/١٠' },
      { id: 'u5', name: 'نورة الدوسري', id_no: '1054321098', phone: '0566778899', district: 'حي النخيل', requests: 6, joined: '١٤٤٥/٠٧/١٨' },
      { id: 'u6', name: 'خالد الشمري', id_no: '1043210987', phone: '0599887766', district: 'حي الملقا', requests: 1, joined: '١٤٤٦/٠٣/٢٢' },
    ],
    requestTrend: { labels: ['صفر', 'محرّم', 'صفر ٢', 'محرّم ٢', 'صفر ٣', 'محرّم ٣'], values: [820, 945, 1010, 1180, 1245, 1380] },
    statusBreakdown: { pending: 24, progress: 36, done: 1248, rejected: 18 },
    districtData: [
      { name: 'حي النخيل', count: 412 }, { name: 'حي الياسمين', count: 318 },
      { name: 'حي الورود', count: 245 }, { name: 'حي الفيصلية', count: 198 },
      { name: 'حي الملقا', count: 154 },
    ],
    avatarSamples: ['ع.ر', 'م.ق', 'ف.ز', 'س.غ', 'ن.د', 'خ.ش', 'ه.م', 'أ.ع', 'ل.ح', 'ي.ق', 'ر.ب', 'ب.ج'],
  },
  en: {
    quickServices: [
      { icon: '🏗️', title: 'Building permit', desc: 'Issue or renew building permits', color: '#e8f3f0', tint: '#0e6b53', cat: 'build', action: 'svc-build' },
      { icon: '🏪', title: 'Business license', desc: 'Open or renew a shop license', color: '#fdf5e3', tint: '#a07a0c', cat: 'business', action: 'svc-biz' },
      { icon: '📋', title: 'Health certificate', desc: 'For food-handlers', color: '#eaf4f8', tint: '#1e6b85', cat: 'health', action: 'svc-health' },
      { icon: '💳', title: 'Pay bill', desc: 'Municipal fees and services', color: '#f0eaf6', tint: '#5e3b8a', cat: 'pay', action: 'svc-pay' },
      { icon: '📢', title: 'Submit complaint', desc: 'Your feedback matters', color: '#fbeae8', tint: '#c0413a', cat: 'complaint', action: 'svc-complaint' },
      { icon: '📑', title: 'Request document', desc: 'To-whom-it-may-concern letters', color: '#e6f5ee', tint: '#2f9c6f', cat: 'build', action: 'svc-doc' },
      { icon: '🅿️', title: 'Parking pass', desc: 'Monthly parking reservation', color: '#fcf0d8', tint: '#c98014', cat: 'pay', action: 'svc-park' },
      { icon: '🔍', title: 'Track request', desc: 'Follow up on a past request', color: '#e3f1ea', tint: '#1c8159', cat: 'build', action: 'svc-track' },
    ],
    services: [
      { id: 'build-1', cat: 'build', icon: '🏗️', title: 'Issue building permit', desc: 'Apply for a new building permit for residential or commercial land', price: 1200, sla: '14 days', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'build-2', cat: 'build', icon: '📐', title: 'Renew building permit', desc: 'Extend an existing building permit for an additional period', price: 600, sla: '7 days', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'build-3', cat: 'build', icon: '🏘️', title: 'Completion certificate', desc: 'Issue a building completion certificate for a finished structure', price: 400, sla: '5 days', color: '#e8f3f0', tint: '#0e6b53' },
      { id: 'biz-1', cat: 'business', icon: '🏪', title: 'Shop license', desc: 'Open a new commercial shop within the municipal zone', price: 800, sla: '10 days', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'biz-2', cat: 'business', icon: '♻️', title: 'Business renewal', desc: 'Renew an existing business license for one year', price: 500, sla: '5 days', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'biz-3', cat: 'business', icon: '🍽️', title: 'Restaurant / café license', desc: 'License a restaurant or café under health and safety regulations', price: 1500, sla: '14 days', color: '#fdf5e3', tint: '#a07a0c' },
      { id: 'health-1', cat: 'health', icon: '🩺', title: 'Health certificate', desc: 'Health certificate for food-handlers', price: 100, sla: '3 days', color: '#eaf4f8', tint: '#1e6b85' },
      { id: 'health-2', cat: 'health', icon: '🛡️', title: 'Safety certificate', desc: 'Safety inspection for a building or commercial facility', price: 350, sla: '7 days', color: '#eaf4f8', tint: '#1e6b85' },
      { id: 'comp-1', cat: 'complaint', icon: '🚧', title: 'Report a violation', desc: 'Report illegal construction or encroachment on public property', price: 0, sla: 'Immediate', color: '#fbeae8', tint: '#c0413a' },
      { id: 'comp-2', cat: 'complaint', icon: '💡', title: 'Report an issue', desc: 'Broken streetlight, waste container, or public facility', price: 0, sla: 'Immediate', color: '#fbeae8', tint: '#c0413a' },
      { id: 'pay-1', cat: 'pay', icon: '💧', title: 'Pay service fees', desc: 'Pay cleaning, lighting and public service fees', price: 0, sla: 'Immediate', color: '#f0eaf6', tint: '#5e3b8a' },
      { id: 'pay-2', cat: 'pay', icon: '🅿️', title: 'Parking subscription', desc: 'Reserve a monthly parking spot near your home or office', price: 250, sla: 'Immediate', color: '#f0eaf6', tint: '#5e3b8a' },
    ],
    news: [
      { id: 'n1', date: '15 Muharram 1447', cat: 'Announcement', title: 'Building permit renewal now fully online', excerpt: 'Al-Nakheel Municipality announces that building permit renewals are now available through the online portal, no need to visit the HQ — part of the ongoing digital transformation.', img: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1200&q=80', hero: true },
      { id: 'n2', date: '12 Muharram 1447', cat: 'Events', title: 'Opening of Al-Nakheel Central Park', img: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&w=800&q=80' },
      { id: 'n3', date: '10 Muharram 1447', cat: 'Development', title: 'King Fahd Road upgrade works begin', img: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80' },
      { id: 'n4', date: '7 Muharram 1447', cat: 'Health', title: 'Inspection campaign on restaurants and cafés', img: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80' },
      { id: 'n5', date: '5 Muharram 1447', cat: 'Circular', title: 'Updated building code requirements', img: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80' },
    ],
    userRequests: [
      { id: 'R-2026-08921', type: 'Building permit', status: 'progress', progress: 64, date: '12 Muharram 1447', cost: 1200, priority: 'high' },
      { id: 'R-2026-08874', type: 'Business license', status: 'pending', progress: 25, date: '10 Muharram 1447', cost: 800, priority: 'normal' },
      { id: 'R-2026-08820', type: 'Health certificate', status: 'done', progress: 100, date: '2 Muharram 1447', cost: 100, priority: 'normal' },
      { id: 'R-2026-08755', type: 'Service fees', status: 'done', progress: 100, date: '28 Safar 1446', cost: 350, priority: 'low' },
    ],
    bills: [
      { id: 'B-2026-0114', type: 'Service fees — Muharram', amount: 350, due: '20 Muharram 1447', status: 'pending' },
      { id: 'B-2026-0113', type: 'Parking — January', amount: 250, due: '15 Muharram 1447', status: 'pending' },
      { id: 'B-2026-0112', type: 'Service fees — Safar', amount: 350, due: 'Paid', status: 'paid' },
    ],
    complaints: [
      { id: 'C-2026-0331', subject: 'Streetlight out on Prince Sultan St.', status: 'replied', date: '11 Muharram 1447' },
      { id: 'C-2026-0320', subject: 'Waste accumulation in Yasmeen district', status: 'in-progress', date: '5 Muharram 1447' },
      { id: 'C-2026-0305', subject: 'Pothole in front of Al-Fahd School', status: 'resolved', date: '22 Safar 1446' },
    ],
    notifications: [
      { id: 'nt1', type: 'request', text: 'Your building permit status updated to "In progress"', time: '12 min ago', unread: true },
      { id: 'nt2', type: 'bill', text: 'New bill due: 350 SAR', time: '3 hours ago', unread: true },
      { id: 'nt3', type: 'reply', text: 'Municipality replied to your complaint about the streetlight', time: 'Yesterday', unread: false },
      { id: 'nt4', type: 'news', text: 'New: Building permit renewals go fully online', time: '2 days ago', unread: false },
    ],
    adminRequests: [
      { id: 'R-2026-08921', user: 'Abdulrahman Al-Otaibi', userId: '1098765432', type: 'Building permit', date: '12 Muharram', status: 'progress', priority: 'high', district: 'Al-Nakheel' },
      { id: 'R-2026-08920', user: 'Mohammed Al-Qahtani', userId: '1087654321', type: 'Business license', date: '12 Muharram', status: 'pending', priority: 'normal', district: 'Al-Yasmeen' },
      { id: 'R-2026-08919', user: 'Fatima Al-Zahrani', userId: '1076543210', type: 'Health certificate', date: '11 Muharram', status: 'pending', priority: 'normal', district: 'Al-Wurood' },
      { id: 'R-2026-08918', user: 'Saeed Al-Ghamdi', userId: '1065432109', type: 'Building', date: '11 Muharram', status: 'progress', priority: 'high', district: 'Al-Faisaliya' },
      { id: 'R-2026-08917', user: 'Noura Al-Dosari', userId: '1054321098', type: 'Permit renewal', date: '10 Muharram', status: 'done', priority: 'low', district: 'Al-Nakheel' },
      { id: 'R-2026-08916', user: 'Khaled Al-Shammari', userId: '1043210987', type: 'Safety cert.', date: '10 Muharram', status: 'progress', priority: 'normal', district: 'Al-Malqa' },
      { id: 'R-2026-08915', user: 'Hind Al-Maliki', userId: '1032109876', type: 'Building permit', date: '9 Muharram', status: 'rejected', priority: 'normal', district: 'Al-Aqeeq' },
      { id: 'R-2026-08914', user: 'Ahmed Al-Omari', userId: '1021098765', type: 'Restaurant lic.', date: '9 Muharram', status: 'pending', priority: 'high', district: 'Al-Nuzha' },
      { id: 'R-2026-08913', user: 'Lina Al-Harbi', userId: '1010987654', type: 'Fee payment', date: '8 Muharram', status: 'done', priority: 'low', district: 'Al-Nakheel' },
      { id: 'R-2026-08912', user: 'Yousef Al-Qarni', userId: '1009876543', type: 'Building', date: '8 Muharram', status: 'progress', priority: 'normal', district: 'Al-Yasmeen' },
      { id: 'R-2026-08911', user: 'Reem Al-Balawi', userId: '1098765430', type: 'Parking pass', date: '7 Muharram', status: 'done', priority: 'low', district: 'Al-Wurood' },
      { id: 'R-2026-08910', user: 'Badr Al-Juhani', userId: '1087654320', type: 'Health certificate', date: '7 Muharram', status: 'progress', priority: 'normal', district: 'Al-Faisaliya' },
    ],
    adminServices: [
      { id: 's1', name: 'Issue building permit', cat: 'build', fee: 1200, sla: '14', active: true, count: 1245 },
      { id: 's2', name: 'Renew building permit', cat: 'build', fee: 600, sla: '7', active: true, count: 832 },
      { id: 's3', name: 'Shop license', cat: 'business', fee: 800, sla: '10', active: true, count: 654 },
      { id: 's4', name: 'Business renewal', cat: 'business', fee: 500, sla: '5', active: true, count: 1208 },
      { id: 's5', name: 'Health certificate', cat: 'health', fee: 100, sla: '3', active: true, count: 2890 },
      { id: 's6', name: 'Safety certificate', cat: 'health', fee: 350, sla: '7', active: true, count: 412 },
      { id: 's7', name: 'Parking subscription', cat: 'pay', fee: 250, sla: '1', active: true, count: 1850 },
      { id: 's8', name: 'Pay service fees', cat: 'pay', fee: 0, sla: '0', active: true, count: 5621 },
      { id: 's9', name: 'Building violation report', cat: 'complaint', fee: 0, sla: '1', active: true, count: 187 },
      { id: 's10', name: 'Report an issue', cat: 'complaint', fee: 0, sla: '1', active: false, count: 92 },
    ],
    adminComplaints: [
      { id: 'C-2026-0331', user: 'Ahmed Al-Omari', subject: 'Streetlight out on Prince Sultan St.', district: 'Al-Nuzha', date: '11 Muharram', status: 'pending' },
      { id: 'C-2026-0330', user: 'Sarah Al-Subaii', subject: 'Water leak in public park', district: 'Al-Wurood', date: '11 Muharram', status: 'pending' },
      { id: 'C-2026-0329', user: 'Majed Al-Rashidi', subject: 'Waste buildup behind mall', district: 'Al-Yasmeen', date: '10 Muharram', status: 'progress' },
      { id: 'C-2026-0328', user: 'Nawal Al-Otaibi', subject: 'Construction site noise', district: 'Al-Faisaliya', date: '10 Muharram', status: 'progress' },
      { id: 'C-2026-0327', user: 'Fahad Al-Harbi', subject: 'Deep pothole on road', district: 'Al-Malqa', date: '9 Muharram', status: 'pending' },
      { id: 'C-2026-0326', user: 'Amal Al-Qurashi', subject: 'Waste containers not collected', district: 'Al-Nakheel', date: '8 Muharram', status: 'resolved' },
      { id: 'C-2026-0325', user: 'Sultan Al-Zaidi', subject: 'Park maintenance neglected', district: 'Al-Aqeeq', date: '7 Muharram', status: 'resolved' },
    ],
    adminUsers: [
      { id: 'u1', name: 'Abdulrahman Al-Otaibi', id_no: '1098765432', phone: '0501234567', district: 'Al-Nakheel', requests: 8, joined: '12/03/1445' },
      { id: 'u2', name: 'Mohammed Al-Qahtani', id_no: '1087654321', phone: '0509876543', district: 'Al-Yasmeen', requests: 4, joined: '20/01/1446' },
      { id: 'u3', name: 'Fatima Al-Zahrani', id_no: '1076543210', phone: '0551122334', district: 'Al-Wurood', requests: 12, joined: '05/11/1444' },
      { id: 'u4', name: 'Saeed Al-Ghamdi', id_no: '1065432109', phone: '0533445566', district: 'Al-Faisaliya', requests: 2, joined: '10/02/1446' },
      { id: 'u5', name: 'Noura Al-Dosari', id_no: '1054321098', phone: '0566778899', district: 'Al-Nakheel', requests: 6, joined: '18/07/1445' },
      { id: 'u6', name: 'Khaled Al-Shammari', id_no: '1043210987', phone: '0599887766', district: 'Al-Malqa', requests: 1, joined: '22/03/1446' },
    ],
    requestTrend: { labels: ['S1', 'M1', 'S2', 'M2', 'S3', 'M3'], values: [820, 945, 1010, 1180, 1245, 1380] },
    statusBreakdown: { pending: 24, progress: 36, done: 1248, rejected: 18 },
    districtData: [
      { name: 'Al-Nakheel', count: 412 }, { name: 'Al-Yasmeen', count: 318 },
      { name: 'Al-Wurood', count: 245 }, { name: 'Al-Faisaliya', count: 198 },
      { name: 'Al-Malqa', count: 154 },
    ],
    avatarSamples: ['A.O', 'M.Q', 'F.Z', 'S.G', 'N.D', 'K.S', 'H.M', 'A.O', 'L.H', 'Y.Q', 'R.B', 'B.J'],
  },
};

window.STATUS_LABEL = {
  ar: { pending: 'قيد الانتظار', progress: 'قيد المعالجة', done: 'منجزة', rejected: 'مرفوضة', draft: 'مسودة', replied: 'تم الرد', resolved: 'تم الحل', 'in-progress': 'قيد المعالجة', paid: 'مدفوعة' },
  en: { pending: 'Pending', progress: 'In progress', done: 'Completed', rejected: 'Rejected', draft: 'Draft', replied: 'Replied', resolved: 'Resolved', 'in-progress': 'In progress', paid: 'Paid' },
};
window.PRIORITY_LABEL = {
  ar: { high: 'عالية', normal: 'متوسطة', low: 'منخفضة' },
  en: { high: 'High', normal: 'Normal', low: 'Low' },
};
